//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnesXM.Emulator.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SnesXM.Emulator.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROM image is in interleaved format - converting....
        /// </summary>
        internal static string InfoConevrtInterleavedRom {
            get {
                return ResourceManager.GetString("InfoConevrtInterleavedRom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixing swapped ExHiROM....
        /// </summary>
        internal static string InfoFixingSwappedExHiRom {
            get {
                return ResourceManager.GetString("InfoFixingSwappedExHiRom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ROM file header found..
        /// </summary>
        internal static string InfoNoRomHeader {
            get {
                return ResourceManager.GetString("InfoNoRomHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found ROM file header (and ignored it)..
        /// </summary>
        internal static string InfoRomHeaderIgnored {
            get {
                return ResourceManager.GetString("InfoRomHeaderIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found multiple ROM file headers (and ignored them)..
        /// </summary>
        internal static string InfoRomHeaderMultipleIgnored {
            get {
                return ResourceManager.GetString("InfoRomHeaderMultipleIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROM lied about its type! Trying again..
        /// </summary>
        internal static string InfoRomTypeLied {
            get {
                return ResourceManager.GetString("InfoRomTypeLied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try &apos;force no-header&apos; option if the game doesn&apos;t work.
        /// </summary>
        internal static string InfoTryForceNoHeader {
            get {
                return ResourceManager.GetString("InfoTryForceNoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pro Action Replay code - should be 8 hex digits in length..
        /// </summary>
        internal static string InvalidProActionNotHex {
            get {
                return ResourceManager.GetString("InvalidProActionNotHex", resourceCulture);
            }
        }
    }
}
