// <copyright file="ColorizeForm1.Designer.cs" company="Public Domain">
//     Copyright (c) 2017 Nelson Garcia.
// </copyright>

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controls.Editors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal partial class ColorizeForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Controls.Editors.ColorizeForm", typeof(ColorizeForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles btnCancel_Anchor {
            get {
                object obj = ResourceManager.GetObject("btnCancel.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=313,Y=293}.
        /// </summary>
        internal static System.Drawing.Point btnCancel_Location {
            get {
                object obj = ResourceManager.GetObject("btnCancel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=23}.
        /// </summary>
        internal static System.Drawing.Size btnCancel_Size {
            get {
                object obj = ResourceManager.GetObject("btnCancel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 6.
        /// </summary>
        internal static int btnCancel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnCancel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string btnCancel_Text {
            get {
                return ResourceManager.GetString("btnCancel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles btnOK_Anchor {
            get {
                object obj = ResourceManager.GetObject("btnOK.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=232,Y=293}.
        /// </summary>
        internal static System.Drawing.Point btnOK_Location {
            get {
                object obj = ResourceManager.GetObject("btnOK.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=23}.
        /// </summary>
        internal static System.Drawing.Size btnOK_Size {
            get {
                object obj = ResourceManager.GetObject("btnOK.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        internal static int btnOK_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnOK.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string btnOK_Text {
            get {
                return ResourceManager.GetString("btnOK.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles btnReset_Anchor {
            get {
                object obj = ResourceManager.GetObject("btnReset.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=151,Y=293}.
        /// </summary>
        internal static System.Drawing.Point btnReset_Location {
            get {
                object obj = ResourceManager.GetObject("btnReset.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=23}.
        /// </summary>
        internal static System.Drawing.Size btnReset_Size {
            get {
                object obj = ResourceManager.GetObject("btnReset.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        internal static int btnReset_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnReset.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string btnReset_Text {
            get {
                return ResourceManager.GetString("btnReset.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkColorize_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkColorize.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=12,Y=297}.
        /// </summary>
        internal static System.Drawing.Point chkColorize_Location {
            get {
                object obj = ResourceManager.GetObject("chkColorize.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=63, Height=17}.
        /// </summary>
        internal static System.Drawing.Size chkColorize_Size {
            get {
                object obj = ResourceManager.GetObject("chkColorize.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        internal static int chkColorize_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkColorize.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorize.
        /// </summary>
        internal static string chkColorize_Text {
            get {
                return ResourceManager.GetString("chkColorize.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkLuma_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkLuma.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=81,Y=297}.
        /// </summary>
        internal static System.Drawing.Point chkLuma_Location {
            get {
                object obj = ResourceManager.GetObject("chkLuma.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=52, Height=17}.
        /// </summary>
        internal static System.Drawing.Size chkLuma_Size {
            get {
                object obj = ResourceManager.GetObject("chkLuma.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        internal static int chkLuma_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkLuma.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luma.
        /// </summary>
        internal static string chkLuma_Text {
            get {
                return ResourceManager.GetString("chkLuma.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool chkPreview_AutoSize {
            get {
                object obj = ResourceManager.GetObject("chkPreview.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=12,Y=320}.
        /// </summary>
        internal static System.Drawing.Point chkPreview_Location {
            get {
                object obj = ResourceManager.GetObject("chkPreview.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=64, Height=17}.
        /// </summary>
        internal static System.Drawing.Size chkPreview_Size {
            get {
                object obj = ResourceManager.GetObject("chkPreview.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        internal static int chkPreview_TabIndex {
            get {
                object obj = ResourceManager.GetObject("chkPreview.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string chkPreview_Text {
            get {
                return ResourceManager.GetString("chkPreview.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Left, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles gbxColorize_Anchor {
            get {
                object obj = ResourceManager.GetObject("gbxColorize.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=12,Y=12}.
        /// </summary>
        internal static System.Drawing.Point gbxColorize_Location {
            get {
                object obj = ResourceManager.GetObject("gbxColorize.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=376, Height=275}.
        /// </summary>
        internal static System.Drawing.Size gbxColorize_Size {
            get {
                object obj = ResourceManager.GetObject("gbxColorize.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int gbxColorize_TabIndex {
            get {
                object obj = ResourceManager.GetObject("gbxColorize.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblHue_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblHue.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=16}.
        /// </summary>
        internal static System.Drawing.Point lblHue_Location {
            get {
                object obj = ResourceManager.GetObject("lblHue.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=30, Height=13}.
        /// </summary>
        internal static System.Drawing.Size lblHue_Size {
            get {
                object obj = ResourceManager.GetObject("lblHue.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int lblHue_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblHue.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue:.
        /// </summary>
        internal static string lblHue_Text {
            get {
                return ResourceManager.GetString("lblHue.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblLightness_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblLightness.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=144}.
        /// </summary>
        internal static System.Drawing.Point lblLightness_Location {
            get {
                object obj = ResourceManager.GetObject("lblLightness.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=55, Height=13}.
        /// </summary>
        internal static System.Drawing.Size lblLightness_Size {
            get {
                object obj = ResourceManager.GetObject("lblLightness.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int lblLightness_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblLightness.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightness:.
        /// </summary>
        internal static string lblLightness_Text {
            get {
                return ResourceManager.GetString("lblLightness.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblSaturation_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblSaturation.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=80}.
        /// </summary>
        internal static System.Drawing.Point lblSaturation_Location {
            get {
                object obj = ResourceManager.GetObject("lblSaturation.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=58, Height=13}.
        /// </summary>
        internal static System.Drawing.Size lblSaturation_Size {
            get {
                object obj = ResourceManager.GetObject("lblSaturation.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int lblSaturation_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblSaturation.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation:.
        /// </summary>
        internal static string lblSaturation_Text {
            get {
                return ResourceManager.GetString("lblSaturation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblWeight_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblWeight.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=208}.
        /// </summary>
        internal static System.Drawing.Point lblWeight_Location {
            get {
                object obj = ResourceManager.GetObject("lblWeight.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=44, Height=13}.
        /// </summary>
        internal static System.Drawing.Size lblWeight_Size {
            get {
                object obj = ResourceManager.GetObject("lblWeight.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int lblWeight_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblWeight.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight:.
        /// </summary>
        internal static string lblWeight_Text {
            get {
                return ResourceManager.GetString("lblWeight.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Left, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles ltbHue_Anchor {
            get {
                object obj = ResourceManager.GetObject("ltbHue.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=32}.
        /// </summary>
        internal static System.Drawing.Point ltbHue_Location {
            get {
                object obj = ResourceManager.GetObject("ltbHue.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=318, Height=45}.
        /// </summary>
        internal static System.Drawing.Size ltbHue_Size {
            get {
                object obj = ResourceManager.GetObject("ltbHue.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int ltbHue_TabIndex {
            get {
                object obj = ResourceManager.GetObject("ltbHue.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Left, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles ltbLightness_Anchor {
            get {
                object obj = ResourceManager.GetObject("ltbLightness.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=160}.
        /// </summary>
        internal static System.Drawing.Point ltbLightness_Location {
            get {
                object obj = ResourceManager.GetObject("ltbLightness.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=318, Height=45}.
        /// </summary>
        internal static System.Drawing.Size ltbLightness_Size {
            get {
                object obj = ResourceManager.GetObject("ltbLightness.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        internal static int ltbLightness_TabIndex {
            get {
                object obj = ResourceManager.GetObject("ltbLightness.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Left, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles ltbSaturation_Anchor {
            get {
                object obj = ResourceManager.GetObject("ltbSaturation.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=96}.
        /// </summary>
        internal static System.Drawing.Point ltbSaturation_Location {
            get {
                object obj = ResourceManager.GetObject("ltbSaturation.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=318, Height=45}.
        /// </summary>
        internal static System.Drawing.Size ltbSaturation_Size {
            get {
                object obj = ResourceManager.GetObject("ltbSaturation.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        internal static int ltbSaturation_TabIndex {
            get {
                object obj = ResourceManager.GetObject("ltbSaturation.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Left, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles ltnWeight_Anchor {
            get {
                object obj = ResourceManager.GetObject("ltnWeight.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=224}.
        /// </summary>
        internal static System.Drawing.Point ltnWeight_Location {
            get {
                object obj = ResourceManager.GetObject("ltnWeight.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=318, Height=45}.
        /// </summary>
        internal static System.Drawing.Size ltnWeight_Size {
            get {
                object obj = ResourceManager.GetObject("ltnWeight.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 6.
        /// </summary>
        internal static int ltnWeight_TabIndex {
            get {
                object obj = ResourceManager.GetObject("ltnWeight.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles ntbHue_Anchor {
            get {
                object obj = ResourceManager.GetObject("ntbHue.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=330,Y=36}.
        /// </summary>
        internal static System.Drawing.Point ntbHue_Location {
            get {
                object obj = ResourceManager.GetObject("ntbHue.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        internal static int ntbHue_MaxLength {
            get {
                object obj = ResourceManager.GetObject("ntbHue.MaxLength", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=40, Height=20}.
        /// </summary>
        internal static System.Drawing.Size ntbHue_Size {
            get {
                object obj = ResourceManager.GetObject("ntbHue.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        internal static int ntbHue_TabIndex {
            get {
                object obj = ResourceManager.GetObject("ntbHue.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string ntbHue_Text {
            get {
                return ResourceManager.GetString("ntbHue.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.HorizontalAlignment similar to Right.
        /// </summary>
        internal static System.Windows.Forms.HorizontalAlignment ntbHue_TextAlign {
            get {
                object obj = ResourceManager.GetObject("ntbHue.TextAlign", resourceCulture);
                return ((System.Windows.Forms.HorizontalAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles ntbLightness_Anchor {
            get {
                object obj = ResourceManager.GetObject("ntbLightness.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=330,Y=164}.
        /// </summary>
        internal static System.Drawing.Point ntbLightness_Location {
            get {
                object obj = ResourceManager.GetObject("ntbLightness.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        internal static int ntbLightness_MaxLength {
            get {
                object obj = ResourceManager.GetObject("ntbLightness.MaxLength", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=40, Height=20}.
        /// </summary>
        internal static System.Drawing.Size ntbLightness_Size {
            get {
                object obj = ResourceManager.GetObject("ntbLightness.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        internal static int ntbLightness_TabIndex {
            get {
                object obj = ResourceManager.GetObject("ntbLightness.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string ntbLightness_Text {
            get {
                return ResourceManager.GetString("ntbLightness.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.HorizontalAlignment similar to Right.
        /// </summary>
        internal static System.Windows.Forms.HorizontalAlignment ntbLightness_TextAlign {
            get {
                object obj = ResourceManager.GetObject("ntbLightness.TextAlign", resourceCulture);
                return ((System.Windows.Forms.HorizontalAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles ntbSaturation_Anchor {
            get {
                object obj = ResourceManager.GetObject("ntbSaturation.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=330,Y=100}.
        /// </summary>
        internal static System.Drawing.Point ntbSaturation_Location {
            get {
                object obj = ResourceManager.GetObject("ntbSaturation.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        internal static int ntbSaturation_MaxLength {
            get {
                object obj = ResourceManager.GetObject("ntbSaturation.MaxLength", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=40, Height=20}.
        /// </summary>
        internal static System.Drawing.Size ntbSaturation_Size {
            get {
                object obj = ResourceManager.GetObject("ntbSaturation.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        internal static int ntbSaturation_TabIndex {
            get {
                object obj = ResourceManager.GetObject("ntbSaturation.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string ntbSaturation_Text {
            get {
                return ResourceManager.GetString("ntbSaturation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.HorizontalAlignment similar to Right.
        /// </summary>
        internal static System.Windows.Forms.HorizontalAlignment ntbSaturation_TextAlign {
            get {
                object obj = ResourceManager.GetObject("ntbSaturation.TextAlign", resourceCulture);
                return ((System.Windows.Forms.HorizontalAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles ntbWeight_Anchor {
            get {
                object obj = ResourceManager.GetObject("ntbWeight.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=330,Y=228}.
        /// </summary>
        internal static System.Drawing.Point ntbWeight_Location {
            get {
                object obj = ResourceManager.GetObject("ntbWeight.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        internal static int ntbWeight_MaxLength {
            get {
                object obj = ResourceManager.GetObject("ntbWeight.MaxLength", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=40, Height=20}.
        /// </summary>
        internal static System.Drawing.Size ntbWeight_Size {
            get {
                object obj = ResourceManager.GetObject("ntbWeight.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 7.
        /// </summary>
        internal static int ntbWeight_TabIndex {
            get {
                object obj = ResourceManager.GetObject("ntbWeight.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        internal static string ntbWeight_Text {
            get {
                return ResourceManager.GetString("ntbWeight.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.HorizontalAlignment similar to Right.
        /// </summary>
        internal static System.Windows.Forms.HorizontalAlignment ntbWeight_TextAlign {
            get {
                object obj = ResourceManager.GetObject("ntbWeight.TextAlign", resourceCulture);
                return ((System.Windows.Forms.HorizontalAlignment)(obj));
            }
        }
    }
}
