//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helper.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helper.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &apos;{1}&apos; is not valid for &apos;{0}&apos;. &apos;{0}&apos; cannot be negative and must be and less than &apos;{2}&apos;..
        /// </summary>
        internal static string ErrorArrayBounds {
            get {
                return ResourceManager.GetString("ErrorArrayBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &apos;{1}&apos; is not valid for &apos;{0}&apos;. &apos;{0}&apos; exceeds the array range &apos;{3}&apos; of &apos;{2}&apos; from starting index &apos;{4}&apos;..
        /// </summary>
        internal static string ErrorArrayRange {
            get {
                return ResourceManager.GetString("ErrorArrayRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &quot;{1}&quot; for &apos;{0}&apos; is not a string that a full path can be obtained from.\n\n{3}:\n{2}.
        /// </summary>
        internal static string ErrorCannotGetFullPath {
            get {
                return ResourceManager.GetString("ErrorCannotGetFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &quot;{1}&quot; for &apos;{0}&apos; is not a string that a path extension can be obtained from.\n\n{3}:\n{2}.
        /// </summary>
        internal static string ErrorCannotGetPathExtension {
            get {
                return ResourceManager.GetString("ErrorCannotGetPathExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array &apos;{0}&apos; cannot be empty or null..
        /// </summary>
        internal static string ErrorEmptyOrNullArray {
            get {
                return ResourceManager.GetString("ErrorEmptyOrNullArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has data that is in an incorrect format..
        /// </summary>
        internal static string ErrorFileFormat {
            get {
                return ResourceManager.GetString("ErrorFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string ErrorFileFormatName {
            get {
                return ResourceManager.GetString("ErrorFileFormatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid extension name..
        /// </summary>
        internal static string ErrorInvalidExtensionName {
            get {
                return ResourceManager.GetString("ErrorInvalidExtensionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of data is not a valid size for the specified format..
        /// </summary>
        internal static string ErrorInvalidFileDataSize {
            get {
                return ResourceManager.GetString("ErrorInvalidFileDataSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid path name..
        /// </summary>
        internal static string ErrorInvalidPathName {
            get {
                return ResourceManager.GetString("ErrorInvalidPathName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &apos;{1}&apos; is not valid for &apos;{0}&apos;. &apos;{0}&apos; must be greater than {2}..
        /// </summary>
        internal static string ErrorLowerBoundExclusive {
            get {
                return ResourceManager.GetString("ErrorLowerBoundExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &apos;{1}&apos; is not valid for &apos;{0}&apos;. &apos;{0}&apos; must be greater than or equal to {2}..
        /// </summary>
        internal static string ErrorLowerBoundInclusive {
            get {
                return ResourceManager.GetString("ErrorLowerBoundInclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; is a string of insufficient size to get a substring with index &apos;{1}&apos; and length &apos;{2}&apos;..
        /// </summary>
        internal static string ErrorStringSubstringSize {
            get {
                return ResourceManager.GetString("ErrorStringSubstringSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; is less than zero and not equal to the EndOfString value &apos;-1&apos;.\nValue given: {1}.
        /// </summary>
        internal static string ErrorSubstringPointerLength {
            get {
                return ResourceManager.GetString("ErrorSubstringPointerLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &apos;{1}&apos; is not valid for &apos;{0}&apos;. &apos;{0}&apos; must be less than {2}..
        /// </summary>
        internal static string ErrorUpperBoundExclusive {
            get {
                return ResourceManager.GetString("ErrorUpperBoundExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &apos;{1}&apos; is not valid for &apos;{0}&apos;. &apos;{0}&apos; must be less than or equal to {2}..
        /// </summary>
        internal static string ErrorUpperBoundInclusive {
            get {
                return ResourceManager.GetString("ErrorUpperBoundInclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} is infinite. A finite value was expected..
        /// </summary>
        internal static string ErrorValueIsInfinity {
            get {
                return ResourceManager.GetString("ErrorValueIsInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} is NaN. A real number was expected..
        /// </summary>
        internal static string ErrorValueIsNaN {
            get {
                return ResourceManager.GetString("ErrorValueIsNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled{0}{1}.
        /// </summary>
        internal static string UntitledName {
            get {
                return ResourceManager.GetString("UntitledName", resourceCulture);
            }
        }
    }
}
