//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controls.Editors.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Controls.Editors.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chroma:.
        /// </summary>
        internal static string ChromaText {
            get {
                return ResourceManager.GetString("ChromaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A single selection was expected..
        /// </summary>
        internal static string ErrorNotSingleSelection {
            get {
                return ResourceManager.GetString("ErrorNotSingleSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graphics are a pixel map for the editor..
        /// </summary>
        internal static string GfxFileDescription {
            get {
                return ResourceManager.GetString("GfxFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GFX File.
        /// </summary>
        internal static string GfxFileType {
            get {
                return ResourceManager.GetString("GfxFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightness:.
        /// </summary>
        internal static string LightnessText {
            get {
                return ResourceManager.GetString("LightnessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luma:.
        /// </summary>
        internal static string LumaText {
            get {
                return ResourceManager.GetString("LumaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A palette is the indexed color data the editor will use..
        /// </summary>
        internal static string PaletteFileDescription {
            get {
                return ResourceManager.GetString("PaletteFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette File.
        /// </summary>
        internal static string PaletteFileType {
            get {
                return ResourceManager.GetString("PaletteFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0x{0:X6}.
        /// </summary>
        internal static string PcColorFormat {
            get {
                return ResourceManager.GetString("PcColorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation:.
        /// </summary>
        internal static string SaturationText {
            get {
                return ResourceManager.GetString("SaturationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0x{0:X4}.
        /// </summary>
        internal static string SnesColorFormat {
            get {
                return ResourceManager.GetString("SnesColorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A TileMap creates arranged tiled of the graphics pixel map..
        /// </summary>
        internal static string TileMapFileDescription {
            get {
                return ResourceManager.GetString("TileMapFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilemap File.
        /// </summary>
        internal static string TileMapFileType {
            get {
                return ResourceManager.GetString("TileMapFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16x.
        /// </summary>
        internal static string Zoom16x {
            get {
                return ResourceManager.GetString("Zoom16x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24x.
        /// </summary>
        internal static string Zoom24x {
            get {
                return ResourceManager.GetString("Zoom24x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32x.
        /// </summary>
        internal static string Zoom32x {
            get {
                return ResourceManager.GetString("Zoom32x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8x.
        /// </summary>
        internal static string Zoom8x {
            get {
                return ResourceManager.GetString("Zoom8x", resourceCulture);
            }
        }
    }
}
